apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-reports-deployment
  namespace: spark-reports
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparkreports
  template:
    metadata:
      labels:
        app: sparkreports
    spec:
      serviceAccountName: spark-reports-sa
      containers:
        - name: sparkreports-container
          image: monicamarshall/sparkreports:2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sparkreports-service
  namespace: spark-reports
spec:
  selector:
    app: sparkreports
  ports:
    - name: http
      protocol: TCP
      port: 8600
      targetPort: 8080
  type: LoadBalancer
