name: "Build and push sparkreports Docker image with static tag to Docker Hub"

on:
  push:
    branches:
      - main
env:
  VERSION: $(( $(cat version.txt) + 1 ))

jobs:
  build_push_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR with Maven
        run: mvn clean package --file pom.xml

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t docker.io/monicamarshall/sparkreports:${{ env.VERSION }} .
          docker push docker.io/monicamarshall/sparkreports:${{ env.VERSION }} .
  
  update_k8s_yaml_version_file_with_latest_image_tag:
    runs-on: ubuntu-latest
    needs: build_push_docker_image
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Set Git Config
        run: |
           git config --global user.email "${{ secrets.GIT_EMAIL}}"
           git config --global user.name "${{ secrets.GIT_USERNAME}}"
 
      - name: Update Deployment YAML
        run: |
          git pull
          sed -i "s|image: monicamarshall/sparkreports:.*$|image: monicamarshall/sparkreports:${{ env.VERSION }}|" deployment.yaml
          echo ${{ env.VERSION }} > version.txt
          CURRENT_VERSION=$(cat version.txt)
          git add deployment.yaml version.txt
          git commit -m "Updated deployment yaml and version txt file with sparkreports image tag to ${CURRENT_VERSION}"
          git push

